services:
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rssagregator
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-user}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-qwerty}
    ports:
      - "8080:8080"
    networks:
      - rssagregator

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME:-user}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-qwerty}
      - PGDATA=/data/postgres
      - POSTGRES_DB=rssagregator
    volumes:
      - postgres:/data/postgres
    networks:
      - rssagregator

networks:
  rssagregator:
    driver: bridge

volumes:
  postgres:
